apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-chart.fullname" . }}
data:
  index.html: |
    <html>
      <head>
        <title>{{ .Chart.Name }}</title>
      </head>
      <body>
        <h1>{{ .Values.content }}</h1>
      </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  vault.hcl: |
    # Vault configuration file
    # Start Vault in development mode
    storage "inmem" {}
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }
    disable_mlock = true
    ui = true