apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-chart.fullname" . }}
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "nginx-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: "nginx:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
        {{- if .Values.vaultEnabled }}
        - name: vault-agent
          image: vault:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: VAULT_ADDR
            value: "http://localhost:8200"
          volumeMounts:
          - name: vault-config
            mountPath: /etc/vault
        {{- end }}
      volumes:
        - name: www
          configMap:
            name: {{ include "nginx-chart.fullname" . }}
        - name: vault-config
          configMap:
            name: vault-config